#!/bin/sh

echo "Starting test runner..."


# Path to the Visual Studio Test Console

test_runner="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"

# Path to your test project's output DLL

tests_dll="C:\Users\adam\Desktop\sftg5\SourceCode\TrainYard\x64\Debug\TrainYardTests.dll"

failure_string="Failed:"

testout=`"$test_runner" "$tests_dll"`

if [[ $testout == *"$failure_string"* ]]; then

echo >&2 "Unit tests are not passing! Push aborted!"

exit 1

fi

echo >&2 "All tests run successfully. Proceeding with push."

exit 0